name: unit-tests

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, 'feature/ds-14-unit-tests' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      # Optional: fail PR on changed lockfile formatting, etc.
#      - name: Verify workspace
#        run: npm ls --workspaces

      # Optional: coverage artifact
#      - name: Upload coverage
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: coverage
#          path: |
#            **/coverage/**
